const mongoose = require('mongoose');
const govschema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    hotels:[{
        hotelname:{
            type:String,
            required:true
        },
        number:{
            type:String,
            required:true
        },
        rate:{
            type:String,
            required:false
        },
        link:{
            type:String,
            required:false
        },
        img:{
            type:String,
            required:true
        }
    }],
    Restaurants:[{
    Restaurantsname:{
            type:String,
            required:true
        },
        number:{
            type:String,
            required:true
        },
        rate:{
            type:String,
            required:false
        },
        link:{
            type:String,
            required:false
        },
        img:{
            type:String,
            required:true
        }
    }],
    TOURISTICPLACES:[{
        TOURISTICPLACESname:{
                type:String,
                required:true
            },
            number:{
                type:String,
                required:true
            },
            rate:{
                type:String,
                required:false
            },
            link:{
                type:String,
                required:false
            },
            img:{
                type:String,
                required:true
            }
        }],
        img:{
            type:String,
            required:true
        }
})

module.exports=mongoose.model("governorates",govschema);